server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: daun
    password: 1234

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html


mybatis:
  type-aliases-package: tuning.com.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml

